name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2021-05-26
version: '8.9.16'
project: 'drupal'
datestamp: 1622058139
